.TH SUP 1 sup\-VERSION
.SH NAME
sup - scale user priviledges
.SH SYNOPSIS
.B sup
.RB [ \-hlv ]
.SH DESCRIPTION
sup is a minimal priviledge scalation utility that allow normal
users to run other programs as different user and group.
.P
The configuration is done in config.h at compile time.
.SH OPTIONS
.TP
.B \-h
print help message
.TP
.B \-l
list command whitelist
.TP
.B \-v
prints version information
.SH AUTHOR
pancake <nopcode.org>
