.TH SUP 1 2019-07-02
.SH NAME
sup \- scale user privileges
.SH SYNOPSIS
.B sup
.IR command
[
.IR args
\ ... ]
.br
.B sup -l
.PP
.SH DESCRIPTION
sup is a minimal privilege escalation utility that allows normal users
to run other programs as different user and group. It is "secured" by
hardcofing SHA256 sums of the executables into itself to decide if a
user is actually authorized to run the requested command.
.TP
The configuration is done in config.h at compile time.
.SH OPTIONS
.B \-l
List compiled authorizations
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
